# This is a basic workflow to help you get started with Actio
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: dummy-jobs
        run: |
          #mkdir test
          #cd test
          git clone https://github.com/jeandieb/test-mirror.git
          #ls
          cd test-mirror
          git config --list
          echo some-text  > test.txt
          #git config --global user.email "johnnydib15@gmail.com"
          #git config --global user.name "Jean Dieb"
          #git config --global remote.origin.url "https://github.com/jeandieb/test-mirror.git"
          #git config --global remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
          #git config --global branch.main.remote "origin"
          #git config --global branch.main.merge "refs/heads/main"
          #git remote set-url https://jeandieb:johnny4HUB@github.com/jeandieb/test-mirror.git
          git remote set-url origin https://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@github.com/jeandieb/test-mirror.git
          git pull origin main
          #git config --global --list
          #cmdkey /add:windows-latest /user:jeandieb /pass:${{secrets.GIT_PASSWORD}}
          #cmdkey /list
          #git config --global credential.helper wincred
          git add .
          git commit -m "test push"
          git push origin main
          
#       - name: mirror-repository
#         # You may pin to the exact commit or the version.
#         # uses: yesolutions/mirror-action@082a9611ed4b64c796245a62b34584ee2ded6833
#         uses: yesolutions/mirror-action@v0.6.0
#         with:
#           # The remote ref name to use. 'mirror' by default. Useful to avoid conflicts with existing remotes.
#           REMOTE_NAME: mirror
#           # The remote repository e.g. https://github.com/octocat/foo.git or git@github.com:octocat/foo.git
#           REMOTE: https://github.com/jeandieb/test-mirror.git
#           # Username for remote repository
#           GIT_USERNAME: jeandieb
#           # The git https password or token for the remote repository
#           GIT_PASSWORD: ${{secrets.GIT_PASSWORD}}
#           # The ssh private key for writing to the remote repository, if using ssh
#           #GIT_SSH_PRIVATE_KEY: # optional
#           # The ssh public key for writing to the remote repository. Normally, not required at all
#           #GIT_SSH_PUBLIC_KEY: # optional
#           # The contents of a SSH known_hosts file for host key verification
#           #GIT_SSH_KNOWN_HOSTS: # optional
#           # if true, skips host key verification. Mutually exclusive with GIT_SSH_KNOWN_HOSTS
#           #GIT_SSH_NO_VERIFY_HOST: # optional, default is false
#           # Push all refs instead of just the current branch
#           #PUSH_ALL_REFS: # optional, default is true
#           # The arugments to use when pushing the repository
#           #GIT_PUSH_ARGS: # optional, default is --tags --force --prune
#           # set to "true" to enable debug mode
#           DEBUG: true
