# This is a basic workflow to help you get started with Action
name: Mirror

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Push_Changes:
    name: Push Changes to Target
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: copy-paste-push
        run: |
          pwd
          ls
          cd
          pwd
          git clone https://github.com/jeandieb/test-mirror.git
          pwd
          ls
          #sudo cp /home/runner/work/github-actions/github-actions/test-copy.txt /home/runner/work/github-actions/test-mirror
          #cd test-mirror
          #git remote set-url origin https://${{secrets.GIT_PAT}}@github.com/jeandieb/test-mirror
          #git config --global user.email ""
          #git config --global user.name "Johnny Dib"
          #touch from-action.txt
          #git add test-copy.txt
          #git commit -m "pushing from actions"
          #git push origin main
          
